export const SET_CATEGORIES = 'SET_CATEGORIES'
export const SET_CATEGORY_INFO = 'SET_CATEGORY_INFO'
export const CLEAR_CATEGORY_INFO = 'CLEAR_CATEGORY_INFO'

export const SET_PRODUCT_DETAILS = 'SET_PRODUCT_DETAILS'
export const CLEAR_PRODUCT_DETAILS = 'CLEAR_PRODUCT_DETAILS'
export const SET_PRODUCTS = 'SET_PRODUCTS'
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS'
export const SET_PRODUCTS_SCROLL_OFFSET = 'SET_PRODUCTS_SCROLL_OFFSET'
export const SET_PRODUCTS_SEARCH = 'SET_PRODUCTS_SEARCH'
export const CLEAR_PRODUCTS_SEARCH = 'CLEAR_PRODUCTS_SEARCH'
export const SET_CART_PRODUCTS = 'SET_CART_PRODUCTS'
export const ADD_CART_PRODUCT = 'ADD_CART_PRODUCT'
export const REMOVE_CART_PRODUCT = 'REMOVE_CART_PRODUCT'
export const CHANGE_CART_PRODUCT_QUANTITY = 'CHANGE_CART_PRODUCT_QUANTITY'
export const CLEAR_CART = 'CLEAR_CART'
export const SET_SEARCH_PRODUCTS = 'SET_SEARCH_PRODUCTS'

/** Favorite products */
export const SET_FAVORITE_PRODUCTS = 'SET_FAVORITE_PRODUCTS'
export const TOGGLE_FAVORITE_PRODUCT = 'TOGGLE_FAVORITE_PRODUCT'
export const SET_FAVORITE_SUBCATEGORIES = 'SET_FAVORITE_SUBCATEGORIES'

export const SET_USER_INFO = 'SET_USER_INFO'
export const LOGOUT = 'LOGOUT'

export const OVERLAY_SHOW = 'OVERLAY_SHOW'
export const OVERLAY_HIDE = 'OVERLAY_HIDE'
export const OVERLAY_SETUP = 'OVERLAY_SETUP'

/** Orders */
export const SET_ORDERS = 'SET_ORDERS'
export const SET_ORDER_DETAILS = 'SET_ORDER_DETAILS'
export const CLEAR_ORDER_DETAILS = 'CLEAR_ORDER_DETAILS'
export const SET_LAST_ACTIVE_ORDER = 'SET_LAST_ACTIVE_ORDER'

/** Warehouses lists */
export const SET_WAREHOUSES = 'SET_WAREHOUSES'
export const SET_ACTIVE_WAREHOUSE = 'SET_ACTIVE_WAREHOUSE'
export const CLEAR_WAREHOUSES = 'CLEAR_WAREHOUSES'

/** Residences lists */
export const SET_RESIDENCES = 'SET_RESIDENCES'
export const CLEAR_RESIDENCES = 'CLEAR_RESIDENCES'

/** Auth  */
export const SET_AUTH_ERROR = 'SET_AUTH_ERROR'
export const SET_ACTIVE_AUTH_STEP = 'SET_ACTIVE_AUTH_STEP'
export const INCREMENT_ACTIVE_AUTH_STEP = 'INCREMENT_ACTIVE_AUTH_STEP'
export const DECREMENT_ACTIVE_AUTH_STEP = 'DECREMENT_ACTIVE_AUTH_STEP'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const CLEAR_AUTH = 'CLEAR_AUTH'
export const UPDATE_AUTH_USER = 'UPDATE_AUTH_USER'

/** Seach */
export const SET_SEARCH = 'SET_SEARCH'
export const CLEAR_SEARCH = 'CLEAR_SEARCH'
